### ISSUE TITLE
first generated psf is not centered

### ISSUE THREAD

**Issue by micropolimi** [andreabassi78/napari-psf-simulator#3] opened 2022-05-20 15:32 UTC
The very first generated psf is not centered and it's and the airy disk in not visible.
It's centered instead from the second execution.
It'd be nice to align this

**Comment by andreabassi78** [comment] 2022-05-20 16:04
Can't reproduce the error. What version of the plugin are you using and what's your napari version? Thanks

**Comment by micropolimi** [comment] 2022-05-22 08:52
napari 0.4.14
napari-psf-simulator 0.1.4

**Comment by andreabassi78** [comment] 2022-05-23 06:17
Ok, it looks like that the viewer.dims class has been modified recently. I'm having a similar problem using viewer.dims.point(), which gives inconsistent results with different napari versions. I'll search for the recommended usage. Please write here if you have any ideas.

**Comment by andreabassi78** [comment] 2022-06-08 21:54
Hi @micropolimi, [I added this line to reset the view.](https://github.com/andreabassi78/napari-psf-simulator/blob/17b9d7bdfd146daae8c8c93ea14b2a3be13f149e/src/napari_psf_simulator/_widget.py#L294) The issue is solved for napari-psf-simulator >=0.1.5
Due to a previous issue in napari,  the new change raises an error if napari <0.4.13 is installed.
Considering that you many users are updating napari regularly, this point can be considered a minor issue. I am closing the issue

**Closed as completed by andreabassi78** 2022-06-08 21:54 UTC
Labels: invalid
